import { VirtualizedList } from "react-native";
import Residance from "../../pages/Merchant/Residance";
import DryClean from "../../pages/DryClean/DryClean";

export const images = {
Vlogo: require('../images/Vlogo.png'),
Logo: require('../images/Logo.png'),
Curve: require('../images/curve.png'),
Car: require('../images/car3.png'),
carPick: require('../images/carPick.png'),
bikePick: require('../images/bikePick.png'),
Facebook: require('../images/Facebook.png'),
Google: require('../images/Googles.png'),
Apple: require('../images/Apple.png'),
VerifyOTP: require('../images/VerifyOtp.png'),
SuccessOTP: require('../images/OTPSucess.png'),
EmailOTP: require('../images/EmailOTP.png'),
EmailSuccess: require('../images/EmailSuccess.png'),
Forgot: require('../images/Forgot.png'),
profileImage: require('../images/Profile.png'),
Path1: require('../images/Path1.png'),
Path2: require('../images/Path2.png'),
Path3: require('../images/Path3.png'),
CarSlider: require('../images/CARSlider.png'),
Scanner: require('../images/scan.png'),
Ride: require('../images/Group8785.png'),
Parking: require('../images/Group8787.png'),
Cleaning: require('../images/Group9719.png'),
User: require('../images/Component.png'),
Business: require('../images/business.png'),
Driver: require('../images/Group87.png'),
wallet: require('../images/wallet.png'),
live: require('../images/Live.png'),
location: require('../images/location.png'),
history: require('../images/HistoryClock.png'),
contactImage: require('../images/contactImage.png'),
success: require('../images/success.png'),
calender: require('../images/calendar.png'),
floor1: require('../images/floor1.png'),
floor2: require('../images/floor2.png'),
floor3: require('../images/floor3.png'),
garage: require('../images/garage.png'),
residence: require('../images/residence.png'),
BookingConfirmationMap: require('../images/BookingConfirmationMap.png'),
applePay: require('../images/applePay.png'),
mastercard: require('../images/mastercard.png'),
visa: require('../images/visa.png'),
waylet: require('../images/waylet.png'),
camera: require('../images/camera.png'),
user: require('../images/user.png'),
CarTop: require('../images/CarTop.png'),
backbutton: require('../images/back-arrow.png'),
pickup: require('../images/pickup.png'),
person: require('../images/noperson.png'),
historypark: require('../images/historypark.png'),
user1: require('../images/user1.png'),
currentlocation: require('../images/currentlocation.png'),
targetmarker: require('../images/targetmarker.png'),
washing: require('../images/washing.png'),
delete: require('../images/deleteimg.png'),
home: require('../images/home.png'),
business: require('../images/business.png'),
dropdownarrow: require('../images/dropdown.png'),
myLocation: require('../images/myLocation.png'),
pen: require('../images/pen.png'),
path: require('../images/routepath.png'),
dialer: require('../images/dialer.png'),
cleanerimg: require('../images/cleanerimg.png'),
defaultProfile: require('../images/defaultProfile.png'),
cardFont: require('../images/cardFont.png'),
cardBack: require('../images/cardBack.png'),
BGmap: require('../images/BGmap.png'),
MerchantParkLot: require('../images/MerchantParkLot.png'),
MerchantLOT: require('../images/MerchantLOT.png'),
Residance: require('../images/Residance.png'),
DryClean: require('../images/DryClean.png'),
bus:require('../images/bus.png'),
train: require('../images/train.png'),
arrowicon: require('../images/arrowicon.png'),
history1: require('../images/history.png'),
upcoming: require('../images/upcoming.png'),
busstation: require('../images/busstation.png'),
usalocation: require('../images/usalocation.png'),
Calender: require('../images/Calender.png'),

search: require('../images/Search.png'),
bus1: require('../images/bus1.png'),
train1: require('../images/train1.png'),
routepath: require('../images/routepathh.png'),
newbus: require('../images/newbus.png'),
busroute: require('../images/busroute.png'),
filter2: require('../images/filter2.png'),
trainroute: require('../images/trainroute.png'),
clock: require('../images/clock.png'),
check: require('../images/check.png'),
buscancel: require('../images/buscancel.png'),
traincancel: require('../images/traincancel.png'),
caretup: require('../images/caretup.png'),
caretdown: require('../images/caretdown.png'),

FoodDelivery: require('../images/FoodDelivery.png'),
MicroMobility: require('../images/MicroMobility.png'),
bmw : require('../images/bmw.png'),
mtb : require('../images/cycle.png'),
star : require('../images/star.png'),
timeclock: require('../images/timeclock.png'),
blackperson:require('../images/blackperson.png'),
scooter:require('../images/scooter.png'),
mycycle:require('../images/mycycle.png'),
ceobike:require('../images/ceobike.png'),
userlocate:require('../images/userlocate.png'),
bikepath:require('../images/bikepath.png'),
leftarrow:require('../images/leftarrow.png'),
rightarrow:require('../images/rightarrow.png'),
bmw1:require('../images/bmw1.png'),
scooter_icon:require('../images/scooter_icon.png'),
bike_icon:require('../images/bike_icon.png'),
bicycle_icon:require('../images/bicycle_icon.png'),
vespa_icon:require('../images/vespa_icon.png'),
scooter1:require('../images/scooter1.png'),
scooter2:require('../images/scooter2.png'),
scooter3:require('../images/scooter3.png'),
bicycle1:require('../images/bicycle1.png'),
bicycle2:require('../images/bicycle2.png'),
vespa1:require('../images/vespa1.png'),
vespa2:require('../images/vespa2.png'),
bmw2:require('../images/bmw2.png'),
bmw3:require('../images/bmw3.png'),
arrow1:require('../images/arrow1.png'),
bookingsuccess: require('../images/bookingsuccess.png'),
doc1:require('../images/doc1.png'),
doc2:require('../images/doc2.png'),
doc3:require('../images/doc3.png'),
starEmpty: require('../images/starEmpty.png'),
expand: require('../images/expand.png'),
currentlocation1: require('../images/currentlocation1.png'),
bar1:require('../images/bar1.png'),
location2: require('../images/location2.png'),
man1: require('../images/man.png'),
man2: require('../images/man1.png'),
washing2: require('../images/washing2.png'),
route1: require('../images/route1.png'),

careconomy: require('../images/careconomy.png'),
carpremium: require('../images/carpremium.png'),
carroute1: require('../images/carroute1.png'),
carlocation1: require('../images/carlocation1.png'),
cross: require('../images/cross.png'),
ridecancelled: require('../images/ridecancelled.png'),
cancelledsuccess: require('../images/cancelledsuccess.png'),
record: require('../images/record.png'),
map: require('../images/Background.png'),
childVideo: require('../images/childvideo.png'),
close1: require('../images/close1.png'),
childimage: require('../images/childimage.png'),
keys: require('../images/keys.png'),
sidecar:require('../images/sidecar.png'),
sedan: require('../images/sedan.png'),
freemovie:require('../images/freemovie.png'),
carbooked:require('../images/carbooked.png'),
edit: require('../images/edit.png'),
delete1: require('../images/delete1.png'),
car1: require('../images/car1.png'),
delete2: require('../images/delete2.png'),

TukTuk: require('../images/TukTuk.png'),
Pizza: require('../images/Pizza.png'),
Burger: require('../images/Burger.png'),
Sandwich: require('../images/Sandwich.png'),
Desserts: require('../images/Desserts.png'),
Soup: require('../images/Soup.png'),
PizzaCart: require('../images/PizzaCart.png'),
BurgerByBella: require('../images/BurgerByBella.png'),
CafeDe: require('../images/CafeDE.png'),
FOODImage: require('../images/FOODImage.png'),
IcCart: require('../images/IcCart.png'),
PlaceNewOrder: require('../images/PlaceNewOrder.png'),
IcCartOrange: require('../images/IcCartOrange.png'),

}
